#=-=-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=
# 死亡惩罚 重制版  DeathPenalty Reloaded
# Author: Stiven D. <admin@sgsd.pw>
# Original: leeyao
#=-=-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=
#掉落钱  可以为固定值也可以为百分比
Money: '10%'
#掉落经验  可以为固定值也可以为百分比
Exp: '10%'
#掉落物品  固定值整数
Item: 6
#经验掉落后，是否产生经验球
Summonxp: true
#物品掉落忽略物品，只能使用数字ID
Bypass: 
- '387'
- '264'
#死亡buff设置
Buff:
  #迟缓状态持续时间
  SlowTime: 5
  #失明状态持续时间
  BlindnessTime: 5
  #反胃状态持续时间
  ConfusionTime: 5
Message:
  Head: '§d 死亡惩罚 §c§l>> '
  DeathDrop: '§e你因为死亡掉落了: '
  Money: '$'
  Exp: '经验'
  GiveBuff: '§e重生后的一分钟内你感到非常又饿又晕.'
#多世界设置  注意！这里是不启用插件的世界名
Worlds:
- Example
